modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "netjs"
version = "${version}"
displayName = "NetJS (Forge)"
authors = "KostromDan"
description = '''
Addon for KubeJS for very limited safe network interaction.
'''
#logoFile = ""

[[dependencies.netjs]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netjs]]
modId = "architectury"
mandatory = true
versionRange = "[4.7.78,)"
ordering = "AFTER"
side = "BOTH"